; ============================================================
; USART0 Double Speed Mode (U2X0) Test
; ============================================================
; Validates that setting the U2X0 bit correctly shifts the 
; baud rate generation divisor from 16 to 8.
;
; NOTE FOR TESTBENCH (tb_usart.py):
; - The Python harness does NOT need to change its baud rate.
; - By properly recalculating UBRR0 from 10 to 21 on the AVR,
;   the physical baud rate generated by the hardware will exactly
;   match the standard UBRR0=10 timing. If the internal clock 
;   divider fails to shift to 8, a frame error will occur.
; ============================================================

.equ UCSR0A = 0xC0
.equ UCSR0B = 0xC1
.equ UCSR0C = 0xC2
.equ UBRR0L = 0xC4
.equ UBRR0H = 0xC5
.equ UDR0   = 0xC6

.equ RXC0_BIT  = 7
.equ UDRE0_BIT = 5
.equ U2X0_BIT  = 1      ; Double Speed Mode Flag

.equ test_case    = 0x0100
.equ final_result = 0x0101

.org 0x0000
reset:
    ldi r16, high(0x08FF)
    out 0x3E, r16          ; SPH
    ldi r16, low(0x08FF)
    out 0x3D, r16          ; SPL

    ldi r16, 1
    sts test_case, r16
    sts final_result, r16

    ; --- 1. Enable Double Speed Mode ---
    ; Must write a 1 to U2X0 in UCSR0A. 
    ldi r16, (1 << U2X0_BIT)
    sts UCSR0A, r16

    ; --- 2. Set Recalculated UBRR0 ---
    ; UBRR0 = 21 yields the same baud rate in U2X0=1 mode 
    ; as UBRR0 = 10 does in normal U2X0=0 mode.
    ldi r16, 21
    sts UBRR0L, r16
    ldi r16, 0
    sts UBRR0H, r16

    ; --- 3. Standard Configuration ---
    ldi r16, 0x06           ; async, no parity, 1 stop, 8 data bits
    sts UCSR0C, r16
    ldi r16, 0x18           ; RXEN0 | TXEN0
    sts UCSR0B, r16

    rjmp test_u2x0_start

; ============================================================
; TEST 1: Double Speed Transmission and Reception
; ============================================================
test_u2x0_start:
wait_udre:
    lds r16, UCSR0A
    sbrs r16, UDRE0_BIT
    rjmp wait_udre

    ; Send a test byte. The python loopback harness should receive 
    ; it cleanly because the physical timing remains untouched.
    ldi r18, 0x77
    sts UDR0, r18

wait_rxc:
    lds r16, UCSR0A
    sbrs r16, RXC0_BIT
    rjmp wait_rxc

    ; Read the echoed byte. If U2X0 logic failed, this byte 
    ; will be corrupted or missing due to severe timing mismatch.
    lds r17, UDR0
    cpi r17, 0x77
    brne fail

    rcall inc_case
    rjmp success

; ============================================================
; Helpers
; ============================================================
inc_case:
    lds r16, test_case
    inc r16
    sts test_case, r16
    ret

; ============================================================
; SUCCESS / FAILURE
; ============================================================
success:
    ldi r16, 1
    sts final_result, r16
end:
    rjmp end

fail:
    ldi r16, 255
    sts final_result, r16
    rjmp end