#!/usr/bin/env python3
"""
gen_hex_images.py — assemble all test_*.asm files with avra and emit
avr_hex_images.h / avr_hex_images.c containing the compiled machine
code as const C byte arrays, plus a small lookup table + accessors.

Usage:
    python3 gen_hex_images.py <asm_dir> <output_dir>

Requires `avra` on PATH (Debian/Ubuntu: `apt-get install avra`).

Re-run this any time you add/edit a test_*.asm file — it's meant to be
a build step (e.g. a PlatformIO pre-build script), not hand-maintained.
"""
import re
import subprocess
import sys
from pathlib import Path

HEADER_TEMPLATE = """#ifndef AVR_HEX_IMAGES_H_
#define AVR_HEX_IMAGES_H_

#include <stdint.h>

/* Auto-generated by tools/gen_hex_images.py — do not hand-edit. */

typedef struct {
    const char *name;
    const uint8_t *data;
    uint16_t len;
} avr_hex_image_t;

extern const avr_hex_image_t g_avr_hex_images[];
extern const uint16_t g_avr_hex_images_count;

/** Look up a compiled test image by name (e.g. "arith_ADD"). */
int hex_image_get_by_name(const char *name, const uint8_t **out_data, uint16_t *out_len);

/** Look up a compiled test image by table index. */
int hex_image_get_by_index(uint16_t index, const avr_hex_image_t **out);

#endif /* AVR_HEX_IMAGES_H_ */
"""

C_FOOTER_TEMPLATE = """
const avr_hex_image_t g_avr_hex_images[] = {{
{table_rows}
}};

const uint16_t g_avr_hex_images_count = {count}U;

int hex_image_get_by_name(const char *name, const uint8_t **out_data, uint16_t *out_len)
{{
    for (uint16_t i = 0; i < g_avr_hex_images_count; i++) {{
        if (strcmp(g_avr_hex_images[i].name, name) == 0) {{
            *out_data = g_avr_hex_images[i].data;
            *out_len = g_avr_hex_images[i].len;
            return 0;
        }}
    }}
    return -1;
}}

int hex_image_get_by_index(uint16_t index, const avr_hex_image_t **out)
{{
    if (index >= g_avr_hex_images_count) {{
        return -1;
    }}
    *out = &g_avr_hex_images[index];
    return 0;
}}
"""


def assemble(asm_path: Path, work_dir: Path) -> Path | None:
    """Run avra on a copy of asm_path inside work_dir. Returns .hex path or None."""
    local = work_dir / asm_path.name
    local.write_bytes(asm_path.read_bytes())
    result = subprocess.run(["avra", local.name], cwd=work_dir,
                             capture_output=True, text=True)
    hex_path = local.with_suffix(".hex")
    if not hex_path.exists():
        print(f"  SKIP {asm_path.name}: assembly failed", file=sys.stderr)
        for line in result.stdout.splitlines():
            if "Error" in line:
                print(f"        {line.strip()}", file=sys.stderr)
        return None
    return hex_path


def parse_intel_hex(hex_path: Path) -> bytes:
    """Minimal Intel HEX parser: supports record types 00/01/02/04."""
    base = 0
    image: dict[int, int] = {}
    for line in hex_path.read_text().splitlines():
        line = line.strip()
        if not line.startswith(":"):
            continue
        length = int(line[1:3], 16)
        addr = int(line[3:7], 16)
        rtype = int(line[7:9], 16)
        data = line[9:9 + length * 2]
        if rtype == 0x00:
            for i in range(length):
                byte = int(data[i * 2:i * 2 + 2], 16)
                image[base + addr + i] = byte
        elif rtype == 0x02:
            base = int(data, 16) * 16
        elif rtype == 0x04:
            base = int(data, 16) << 16
        elif rtype == 0x01:
            break
    if not image:
        return b""
    top = max(image) + 1
    return bytes(image.get(i, 0xFF) for i in range(top))


def c_identifier(test_name: str) -> str:
    return "g_image_" + re.sub(r"[^A-Za-z0-9_]", "_", test_name)


def format_bytes_as_c_array(data: bytes, ident: str) -> str:
    lines = [f"static const uint8_t {ident}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    asm_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)
    work_dir = out_dir / "_build"
    work_dir.mkdir(exist_ok=True)

    asm_files = sorted(asm_dir.glob("test_*.asm"))
    arrays, rows, skipped = [], [], []

    for asm_path in asm_files:
        test_name = asm_path.stem[len("test_"):]  # e.g. "arith_ADD"
        hex_path = assemble(asm_path, work_dir)
        if hex_path is None:
            skipped.append(test_name)
            continue
        data = parse_intel_hex(hex_path)
        ident = c_identifier(test_name)
        arrays.append(format_bytes_as_c_array(data, ident))
        rows.append(f'    {{"{test_name}", {ident}, {len(data)}U}},')
        print(f"  OK   {asm_path.name}: {len(data)} bytes")

    header = HEADER_TEMPLATE
    body = (
        '#include <string.h>\n#include "avr_hex_images.h"\n\n'
        + "\n\n".join(arrays)
        + "\n"
        + C_FOOTER_TEMPLATE.format(table_rows="\n".join(rows), count=len(rows))
    )

    (out_dir / "avr_hex_images.h").write_text(header)
    (out_dir / "avr_hex_images.c").write_text(body)

    print(f"\nGenerated {len(rows)} images, skipped {len(skipped)}: "
          f"{', '.join(skipped) if skipped else 'none'}")


if __name__ == "__main__":
    main()