import py4hw
import punxa_atmega328p.Memory 

"""
=============================================================================
AI Agent Component Reference: MemoryInterfaceHandler
=============================================================================

Description:
This class manages the Data Memory (SRAM) interface for an AVR-like architecture 
in py4hw. It internally houses and maintains the 16-bit indirect addressing 
pointers (X, Y, Z, and Stack Pointer SP). It handles complex address generation 
including direct addressing, indirect addressing, pointer auto-increment/decrement, 
and displacement addressing (Y+q, Z+q). 

Internal State:
- XregL/XregH, YregL/YregH, ZregL/ZregH: General purpose indirect pointers.
- SPL/SPH: Hardware Stack Pointer.
- BusData: Internal latch for data flowing to/from memory.

Memory Interface (Master/Source):
- Drives: `address`, `write_data` 'read' 'write'
- Reads: `read_data`, 'resp'

Inputs (Control Signals):
- reset (1-bit): Clears all internal pointers and bus states to 0.
- WE (1-bit): Write Enable for loading data into the internal pointer registers.
- LoadSelectMux (int): Selects displacement offsets (not fully mapped in top logic, handled via Q).
- LoadingMux (int): Selects which specific pointer byte (XL, XH, YL, YH, etc.) is updated when WE is high.
- IncDec (int): Controls pointer modification: 0=None, 1=Post-Inc, 2=Pre-Dec, 3=Post-Dec, 4=Pre-Inc.
- ReadWrite (1-bit): 0 = Memory Read, 1 = Memory Write.
- InputSelectMemory (int): MUX selecting the data source for a memory write (DataBus, ResL, ResH, GeneralInput).
- Mem_instruction (int): Opcode determining which pointer to use for address generation (X, Y, Z, SP, ROM, Y+q, Z+q).
- RomAddress (16-bit): Direct memory address input for non-indirect addressing.

Inputs (Data Signals):
- ResL / ResH (8-bit): Low/High byte outputs from the ALU to be written to memory.
- GeneralInput (8-bit): General data bus input. Intended to Load K constantans from the instruction decoder.
- Q (6-bit) : Input for the displacement for 'STD'/'LLD' instructions 

Outputs:
- RegisterOut (8-bit): The latched data read from memory (or echoing written data), sent to the Register File.
- Resp (1-bit): Memory response flag (for handshake routing).
- address_ZL / address_ZH (8-bit): Direct exposure of the Z register for the RomHandler (IJMP/ICALL).

Notes for AI Agents:
When simulating instructions like `LD r16, X+`, this component handles the memory 
read AND the +1 increment of the X register automatically via `IncDec = 1`. 
Displacement values (`q`) are generated by the instruction decoder  for `LDD`/`STD` arrive via a the Q input.
=============================================================================
"""

class MemoryInterfaceHandler(py4hw.Logic):

    # ----------------------------------------------------------
    # Memory instruction encodings
    # ----------------------------------------------------------
    MEM_X = 1
    MEM_X_PLUS = 2
    MEM_Y = 3
    MEM_Y_PLUS = 4
    MEM_Z = 5
    MEM_Z_PLUS = 6
    MEM_SP = 7
    MEM_SP_PLUS = 8
    MEM_RAM_ADDR_REG = 9
    MEM_Y_Q = 10
    MEM_Z_Q = 11
    MEM_RD  = 12   
    MEM_RR  = 13   
    MEM_WB_ADDR = 14  
    MEM_RD_1 = 15
    MEM_RR_1 = 16
    MEM_A_5bit = 17
    MEM_A_6bit = 18

    # --- Input select ---
    INPUT_DATABUS = 1
    INPUT_RESL = 2
    INPUT_RESH = 3
    INPUT_GENERAL = 4
    INPUT_ROM_VALUE = 5
    INPUT_XL = 6
    INPUT_XH = 7
    INPUT_YL = 8
    INPUT_YH = 9
    INPUT_ZL = 10
    INPUT_ZH = 11
    INPUT_SPL = 12
    INPUT_SPH = 13
    INPUT_PCL = 14
    INPUT_PCH = 15
    INPUT_RD_BUFFER = 16

    # --- LoadSelectMux ---
    LOAD_BUS_DATA = 1
    LOAD_XL_MINUS = 2
    LOAD_XH_MINUS = 3
    LOAD_XL_PLUS = 4
    LOAD_XH_PLUS = 5
    LOAD_YL_MINUS = 6
    LOAD_YH_MINUS = 7
    LOAD_YL_PLUS = 8
    LOAD_YH_PLUS = 9
    LOAD_ZL_MINUS = 10
    LOAD_ZH_MINUS = 11
    LOAD_ZL_PLUS = 12
    LOAD_ZH_PLUS = 13

    # --- LoadingMux ---
    LOAD_XL = 1
    LOAD_XH = 2
    LOAD_YL = 3
    LOAD_YH = 4
    LOAD_ZL = 5
    LOAD_ZH = 6
    LOAD_SPL = 7
    LOAD_SPH = 8
    LOAD_RD_BUFFER = 14  

    # --- Increment/Decrement Control ---
    INC_NONE = 0
    INC_POST_INC = 1
    INC_PRE_DEC = 2
    INC_POST_DEC = 3  
    INC_PRE_INC = 4   


    def __init__(self, parent, name: str,
            reset, WE, LoadSelectMux, LoadingMux, IncDec, ReadWrite, InputSelectMemory, 
            Mem_instruction, RomAddress, ResL, ResH, K_val_Input, RomAddressValue,
            PCL_VAL_IN, PCH_VAL_IN, Q, Rd, Rr, A_5bit, A_6bit, WbAddr, memory,
            RegisterOut, Resp, address_ZL, address_ZH, MIH_PCL_LOAD_VAL, MIH_PCH_LOAD_VAL
        ):
        super().__init__(parent, name)

        self.mem = self.addInterfaceSource('memory', memory)

        self.reset = self.addIn('reset', reset)
        self.WE = self.addIn('WE', WE)
        self.LoadSelectMux = self.addIn('LoadSelectMux', LoadSelectMux)
        self.LoadingMux = self.addIn('LoadingMux', LoadingMux)
        self.IncDec = self.addIn('IncDec', IncDec)
        self.ReadWrite = self.addIn('ReadWrite', ReadWrite)
        self.InputSelectMemory = self.addIn('InputSelectMemory', InputSelectMemory)
        self.Mem_instruction = self.addIn('Mem_instruction', Mem_instruction)
        self.RomAddress = self.addIn('RomAddress', RomAddress) 
        self.RomAddressValue = self.addIn('RomHandlerValueRead',RomAddressValue)

        self.PCL_VAL_IN = self.addIn('PCL_VAL_IN',PCL_VAL_IN)
        self.PCH_VAL_IN = self.addIn('PCH_VAL_IN',PCH_VAL_IN)
        self.ResL = self.addIn('ResL', ResL)
        self.ResH = self.addIn('ResH', ResH)
        self.K_val_Input = self.addIn('K_val_Input', K_val_Input)
        self.Q = self.addIn('Q', Q)

        self.Rd = self.addIn('Rd', Rd)
        self.Rr = self.addIn('Rr', Rr)
        self.A_5bit = self.addIn('A_5bit',A_5bit)
        self.A_6bit = self.addIn('A_6bit',A_6bit)
        self.WbAddr = self.addIn('WbAddr', WbAddr)

        self.RegisterOut = self.addOut('RegisterOut', RegisterOut)
        self.Resp = self.addOut('Resp',Resp)
        self.address_ZL = self.addOut('address_ZL',address_ZL)
        self.address_ZH = self.addOut('address_ZH',address_ZH)
        self.MIH_PCL_LOAD_VAL = self.addOut('MIH_PCL_LOAD_VAL',MIH_PCL_LOAD_VAL)
        self.MIH_PCH_LOAD_VAL = self.addOut('MIH_PCH_LOAD_VAL',MIH_PCH_LOAD_VAL)

        self.XregL = 0
        self.XregH = 0
        self.YregL = 0
        self.YregH = 0
        self.ZregL = 0
        self.ZregH = 0
        self.SPL = 0
        self.SPH = 0
        self.RdBuffer = 0  

        self.BusData = 0
        self.Databuffer = 0
        self.debug = 0

    # ==========================================================
    # Helpers
    # ==========================================================

    def getX(self): return (self.XregH << 8) | self.XregL
    def getY(self): return (self.YregH << 8) | self.YregL
    def getZ(self): return (self.ZregH << 8) | self.ZregL
    def getSP(self): return (self.SPH << 8) | self.SPL

    def setX(self, value):
        self.XregL = value & 0xFF
        self.XregH = (value >> 8) & 0xFF

    def setY(self, value):
        self.YregL = value & 0xFF
        self.YregH = (value >> 8) & 0xFF

    def setZ(self, value):
        self.ZregL = value & 0xFF
        self.ZregH = (value >> 8) & 0xFF

    def setSP(self, value):
        self.SPL = value & 0xFF
        self.SPH = (value >> 8) & 0xFF

    # ==========================================================
    # Address generation
    # ==========================================================

    def selectAddress(self):
        mem_instr = self.Mem_instruction.get()
        base_address = 0
        pointer_name = None

        if mem_instr in (self.MEM_X, self.MEM_X_PLUS):
            base_address = self.getX()
            pointer_name = "X"
        elif mem_instr in (self.MEM_Y, self.MEM_Y_PLUS):
            base_address = self.getY()
            pointer_name = "Y"
        elif mem_instr in (self.MEM_Z, self.MEM_Z_PLUS):
            base_address = self.getZ()
            pointer_name = "Z"
        elif mem_instr in (self.MEM_SP, self.MEM_SP_PLUS):
            base_address = self.getSP()
            pointer_name = "SP"
        elif mem_instr == self.MEM_RAM_ADDR_REG:
            base_address = self.RomAddressValue.get()
            pointer_name = "ROM"

        elif mem_instr == self.MEM_RD:
            base_address = self.Rd.get() & 0x1F
            pointer_name = None   

        elif mem_instr == self.MEM_RR:
            base_address = self.Rr.get() & 0x1F
            pointer_name = None

        elif mem_instr == self.MEM_WB_ADDR:
            base_address = self.WbAddr.get() & 0x1F
            pointer_name = None

        elif mem_instr == self.MEM_Y_Q:
            q_val = self.Q.get()
            if q_val & 0x20:
                q_val -= 0x40
            base_address = self.getY() + q_val

        elif mem_instr == self.MEM_Z_Q:
            q_val = self.Q.get()
            if q_val & 0x20:
                q_val -= 0x40
            base_address = self.getZ() + q_val

        elif mem_instr == self.MEM_RD_1:
            base_address = (self.Rd.get()+1) & 0x1F
            pointer_name = None   

        elif mem_instr == self.MEM_RR_1:
            base_address = (self.Rr.get()+1) & 0x1F
            pointer_name = None   

        elif mem_instr == self.MEM_A_5bit:
            base_address = self.A_5bit.get()
            pointer_name = None   

        elif mem_instr == self.MEM_A_6bit:
            base_address = self.A_6bit.get()
            pointer_name = None   
            
        # UPDATED: Apply Pre-decrement OR Pre-increment BEFORE accessing memory 
        mode = self.IncDec.get()
        if pointer_name in ("X", "Y", "Z", "SP"):
            if mode == self.INC_PRE_DEC:
                base_address -= 1
            elif mode == self.INC_PRE_INC:
                base_address += 1

        return base_address & 0xFFFF, pointer_name

    # ==========================================================
    # Address update logic
    # ==========================================================

    def updatePointer(self, ptr_name):
        if ptr_name is None or ptr_name == "ROM":
            return

        mode = self.IncDec.get()
        if mode == self.INC_NONE:
            return

        # UPDATED: Calculate the offset to apply to the pointer based on the mode
        offset = 0
        if mode in (self.INC_PRE_DEC, self.INC_POST_DEC):
            offset = -1
        elif mode in (self.INC_PRE_INC, self.INC_POST_INC):
            offset = 1

        if ptr_name == "X":
            self.setX(self.getX() + offset)
        elif ptr_name == "Y":
            self.setY(self.getY() + offset)
        elif ptr_name == "Z":
            self.setZ(self.getZ() + offset)
        elif ptr_name == "SP":
            self.setSP(self.getSP() + offset)


    # ==========================================================
    # Data source selection
    # ==========================================================

    def selectWriteData(self):
        sel = self.InputSelectMemory.get()

        if sel == self.INPUT_DATABUS:
            return self.mem.read_data.get()
        elif sel == self.INPUT_RESL:
            return self.ResL.get()
        elif sel == self.INPUT_RESH:
            return self.ResH.get()
        elif sel == self.INPUT_GENERAL:
            return self.K_val_Input.get()
        elif sel == self.INPUT_ROM_VALUE:
            return self.RomAddressValue.get()
        
        elif sel == self.INPUT_XL: return self.XregL
        elif sel == self.INPUT_XH: return self.XregH
        elif sel == self.INPUT_YL: return self.YregL
        elif sel == self.INPUT_YH: return self.YregH
        elif sel == self.INPUT_ZL: return self.ZregL
        elif sel == self.INPUT_ZH: return self.ZregH
        elif sel == self.INPUT_SPL: return self.SPL
        elif sel == self.INPUT_SPH: return self.SPH
        
        elif sel == self.INPUT_PCL: return self.PCL_VAL_IN.get()
        elif sel == self.INPUT_PCH: return self.PCH_VAL_IN.get() 
        
        elif sel == self.INPUT_RD_BUFFER: 
            return self.RdBuffer

        return 0

    # ==========================================================
    # Main clocked behavior
    # ==========================================================

    def clock(self):
        # ----------------------------------------------
        # 0. Reset
        # ----------------------------------------------
        if self.reset.get():
            self.XregL = 0
            self.XregH = 0
            self.YregL = 0
            self.YregH = 0
            self.ZregL = 0
            self.ZregH = 0
            self.SPL = self.SPH = 0
            self.BusData = 0
            
            self.RegisterOut.prepare(0)
            self.mem.address.prepare(0)
            self.mem.write_data.prepare(0)
            return

        # ----------------------------------------------
        # 1. Address generation
        # ----------------------------------------------
        address, pointer_name = self.selectAddress()
        self.mem.address.prepare(address)

        # ----------------------------------------------
        # 2. Memory operation & BusData latching
        # ----------------------------------------------
        rw = self.ReadWrite.get()

        if rw == 1:
            self.BusData = self.selectWriteData()
            self.mem.write_data.prepare(self.BusData)
            self.mem.read.prepare(0)
            self.mem.write.prepare(1)
        elif rw == 2:
            self.BusData = self.mem.read_data.get()
            self.mem.read.prepare(1)
            self.mem.write.prepare(0)
        else: 
            self.mem.read.prepare(0)
            self.mem.write.prepare(0)

        self.Resp.prepare(self.mem.resp.get())
        self.RegisterOut.prepare(self.BusData)

        # ----------------------------------------------
        # 3. Register loading
        # ----------------------------------------------
        if self.WE.get():
            load_sel = self.LoadingMux.get()
            data = self.BusData & 0xFF
            
            if load_sel == self.LOAD_XL: self.XregL = data
            elif load_sel == self.LOAD_XH: self.XregH = data
            elif load_sel == self.LOAD_YL: self.YregL = data
            elif load_sel == self.LOAD_YH: self.YregH = data
            elif load_sel == self.LOAD_ZL: self.ZregL = data
            elif load_sel == self.LOAD_ZH: self.ZregH = data
            elif load_sel == self.LOAD_SPL: self.SPL = data
            elif load_sel == self.LOAD_SPH: self.SPH = data
            elif load_sel == self.LOAD_RD_BUFFER: self.RdBuffer = data

        # ----------------------------------------------
        # 4. Pointer update
        # ----------------------------------------------
        self.updatePointer(pointer_name)

        if self.debug == 1:
            state_log = (
                f"MIH_STATE | "
                f"PC: {self.PCH_VAL_IN.get():02X}{self.PCL_VAL_IN.get():02X} | "
                f"X: {self.getX():04X} Y: {self.getY():04X} Z: {self.getZ():04X} SP: {self.getSP():04X} | "
                f"Addr: {address:04X} Bus: {self.BusData:02X} | "
                f"RD_BUFFER: {self.RdBuffer} |"
                f"WE: {self.WE.get()} RW: {rw} Resp: {self.mem.resp.get()}"
            )
            print(state_log)