import py4hw
import punxa_atmega328p.Memory 


"""
=============================================================================
AI Agent Component Reference: MemoryInterfaceHandler
=============================================================================

Description:
This class manages the Data Memory (SRAM) interface for an AVR-like architecture 
in py4hw. It internally houses and maintains the 16-bit indirect addressing 
pointers (X, Y, Z, and Stack Pointer SP). It handles complex address generation 
including direct addressing, indirect addressing, pointer auto-increment/decrement, 
and displacement addressing (Y+q, Z+q). 

Internal State:
- XregL/XregH, YregL/YregH, ZregL/ZregH: General purpose indirect pointers.
- SPL/SPH: Hardware Stack Pointer.
- BusData: Internal latch for data flowing to/from memory.

Memory Interface (Master/Source):
- Drives: `address`, `write_data` 'read' 'write'
- Reads: `read_data`, 'resp'

Inputs (Control Signals):
- reset (1-bit): Clears all internal pointers and bus states to 0.
- WE (1-bit): Write Enable for loading data into the internal pointer registers.
- LoadSelectMux (int): Selects displacement offsets (not fully mapped in top logic, handled via Q).
- LoadingMux (int): Selects which specific pointer byte (XL, XH, YL, YH, etc.) is updated when WE is high.
- IncDec (int): Controls pointer modification: 0=None, 1=Post-Increment, 2=Pre-Decrement.
- ReadWrite (1-bit): 0 = Memory Read, 1 = Memory Write.
- InputSelect (int): MUX selecting the data source for a memory write (DataBus, ResL, ResH, GeneralInput).
- Mem_instruction (int): Opcode determining which pointer to use for address generation (X, Y, Z, SP, ROM, Y+q, Z+q).
- RomAddress (16-bit): Direct memory address input for non-indirect addressing.

Inputs (Data Signals):
- ResL / ResH (8-bit): Low/High byte outputs from the ALU to be written to memory.
- GeneralInput (8-bit): General data bus input. Intended to Load K constantans from the instruction decoder.
- Q (6-bit) : Input for the displacement for 'STD'/'LLD' instructions 

Outputs:
- RegisterOut (8-bit): The latched data read from memory (or echoing written data), sent to the Register File.
- Resp (1-bit): Memory response flag (for handshake routing).
- address_ZL / address_ZH (8-bit): Direct exposure of the Z register for the RomHandler (IJMP/ICALL).

Notes for AI Agents:
When simulating instructions like `LD r16, X+`, this component handles the memory 
read AND the +1 increment of the X register automatically via `IncDec = 1`. 
Displacement values (`q`) are generated by the instruction decoder  for `LDD`/`STD` arrive via a the Q input.
=============================================================================
"""

class MemoryInterfaceHandler(py4hw.Logic):

    # ----------------------------------------------------------
    # Memory instruction encodings
    # ----------------------------------------------------------
    # 1=X, 2=X+, 3=Y, 4=Y+, 5=Z, 6=Z+, 7=SP, 8=SP+, 9=RamAddrReg
    # 10=Y+q, 11=Z+q, 12=Rd (register file, address from Rd input), 13=Rr (register file, address from Rr input)
    MEM_X = 1
    MEM_X_PLUS = 2
    MEM_Y = 3
    MEM_Y_PLUS = 4
    MEM_Z = 5
    MEM_Z_PLUS = 6
    MEM_SP = 7
    MEM_SP_PLUS = 8
    MEM_RAM_ADDR_REG = 9
    MEM_Y_Q = 10
    MEM_Z_Q = 11
    MEM_RD  = 12   # Direct register-file access: address = Rd (0-31)
    MEM_RR  = 13   # Direct register-file access: address = Rr (0-31)
    MEM_WB_ADDR = 14  # Explicit write-back address from WB_Addr port (for Rd+1, R0/R1 in MUL)

    # --- Input select ---
    INPUT_DATABUS = 1
    INPUT_RESL = 2
    INPUT_RESH = 3
    INPUT_GENERAL = 4

    # --- LoadSelectMux ---
    LOAD_BUS_DATA = 1
    LOAD_XL_MINUS = 2
    LOAD_XH_MINUS = 3
    LOAD_XL_PLUS = 4
    LOAD_XH_PLUS = 5
    LOAD_YL_MINUS = 6
    LOAD_YH_MINUS = 7
    LOAD_YL_PLUS = 8
    LOAD_YH_PLUS = 9
    LOAD_ZL_MINUS = 10
    LOAD_ZH_MINUS = 11
    LOAD_ZL_PLUS = 12
    LOAD_ZH_PLUS = 13

    # --- LoadingMux ---
    LOAD_XL = 1
    LOAD_XH = 2
    LOAD_YL = 3
    LOAD_YH = 4
    LOAD_ZL = 5
    LOAD_ZH = 6
    LOAD_SPL = 7
    LOAD_SPH = 8

    # --- Increment/Decrement Control ---
    INC_NONE = 0
    INC_POST_INC = 1
    INC_PRE_DEC = 2


    def __init__(self, parent, name: str,
            # control inputs
            reset, WE, LoadSelectMux, LoadingMux, IncDec, ReadWrite, InputSelect, Mem_instruction, RomAddress,
            # data inputs
            ResL, ResH, 
            #RomHandlerValueRead,
            K_val_Input, 
            PCL_VAL_IN,
            PCH_VAL_IN,
            Q,
            # register-file address inputs (from instruction decoder)
            Rd, Rr,
            # explicit write-back address (from ControlBox, for Rd+1 / R0 / R1 writes)
            WbAddr,
            # memory interface
            memory, # type: MemoryInterface
            # output
            RegisterOut, Resp, 
            address_ZL, address_ZH, # These are for the RomHandler to Jump using this address
        ):
        super().__init__(parent, name)

        # Memory interface
        self.mem = self.addInterfaceSource('memory', memory)

        # Control inputs
        self.reset = self.addIn('reset', reset)
        self.WE = self.addIn('WE', WE)
        self.LoadSelectMux = self.addIn('LoadSelectMux', LoadSelectMux)
        self.LoadingMux = self.addIn('LoadingMux', LoadingMux)
        self.IncDec = self.addIn('IncDec', IncDec)
        self.ReadWrite = self.addIn('ReadWrite', ReadWrite)
        self.InputSelect = self.addIn('InputSelect', InputSelect)
        self.Mem_instruction = self.addIn('Mem_instruction', Mem_instruction)
        self.RomAddress = self.addIn('RomAddress', RomAddress)
        #self.RomHandlerValueRead = self.addIn('RomHandlerValueRead',RomHandlerValueRead)

        # Data inputs
        self.PCL_VAL_IN = self.addIn('PCL_VAL_IN',PCL_VAL_IN)
        self.PCH_VAL_IN = self.addIn('PCH_VAL_IN',PCH_VAL_IN)
        self.ResL = self.addIn('ResL', ResL)
        self.ResH = self.addIn('ResH', ResH)
        self.K_val_Input = self.addIn('K_val_Input', K_val_Input)
        self.Q = self.addIn('Q', Q)

        # Register-file address inputs: the decoded Rd / Rr field from the
        # instruction word.  Used when Mem_instruction == MEM_RD or MEM_RR so
        # that the handler can address registers 0-31 directly in SRAM.
        self.Rd = self.addIn('Rd', Rd)
        self.Rr = self.addIn('Rr', Rr)

        # Explicit write-back address supplied by the ControlBox.
        # Used when Mem_instruction == MEM_WB_ADDR (e.g. Rd+1 for ADIW/MOVW,
        # R0/R1 for MUL family).  5 bits covers all 32 general-purpose registers.
        self.WbAddr = self.addIn('WbAddr', WbAddr)

        # Output
        self.RegisterOut = self.addOut('RegisterOut', RegisterOut)
        self.Resp = self.addOut('Resp',Resp)
        self.address_ZL = self.addOut('address_ZL',address_ZL)
        self.address_ZH = self.addOut('address_ZH',address_ZH)

        # --------------------------------------------------
        # Internal pointer registers
        # --------------------------------------------------
        self.XregL = 0
        self.XregH = 0
        self.YregL = 0
        self.YregH = 0
        self.ZregL = 0
        self.ZregH = 0
        self.SPL = 0
        self.SPH = 0

        # Internal bus register
        self.BusData = 0

    # ==========================================================
    # Helpers
    # ==========================================================

    def getX(self): return (self.XregH << 8) | self.XregL
    def getY(self): return (self.YregH << 8) | self.YregL
    def getZ(self): return (self.ZregH << 8) | self.ZregL
    def getSP(self): return (self.SPH << 8) | self.SPL

    def setX(self, value):
        self.XregL = value & 0xFF
        self.XregH = (value >> 8) & 0xFF

    def setY(self, value):
        self.YregL = value & 0xFF
        self.YregH = (value >> 8) & 0xFF

    def setZ(self, value):
        self.ZregL = value & 0xFF
        self.ZregH = (value >> 8) & 0xFF

    def setSP(self, value):
        self.SPL = value & 0xFF
        self.SPH = (value >> 8) & 0xFF

    # ==========================================================
    # Address generation
    # ==========================================================

    def selectAddress(self):
        mem_instr = self.Mem_instruction.get()
        base_address = 0
        pointer_name = None

        if mem_instr in (self.MEM_X, self.MEM_X_PLUS):
            base_address = self.getX()
            pointer_name = "X"
        elif mem_instr in (self.MEM_Y, self.MEM_Y_PLUS):
            base_address = self.getY()
            pointer_name = "Y"
        elif mem_instr in (self.MEM_Z, self.MEM_Z_PLUS):
            base_address = self.getZ()
            pointer_name = "Z"
        elif mem_instr in (self.MEM_SP, self.MEM_SP_PLUS):
            base_address = self.getSP()
            pointer_name = "SP"
        elif mem_instr == self.MEM_RAM_ADDR_REG:
            base_address = self.RomAddress.get()
            pointer_name = "ROM"

        # --- Direct register-file access (Rd / Rr from decoder) ---
        elif mem_instr == self.MEM_RD:
            # Registers live at SRAM addresses 0x00-0x1F (0-31)
            base_address = self.Rd.get() & 0x1F
            pointer_name = None   # no pointer to update after the access

        elif mem_instr == self.MEM_RR:
            base_address = self.Rr.get() & 0x1F
            pointer_name = None

        elif mem_instr == self.MEM_WB_ADDR:
            # Explicit address from ControlBox (Rd+1, R0, R1, etc.)
            base_address = self.WbAddr.get() & 0x1F
            pointer_name = None

        # --- Displacement Addressing ---
        elif mem_instr == self.MEM_Y_Q:
            q_val = self.Q.get()
            if q_val & 0x20:
                q_val -= 0x40
            base_address = self.getY() + q_val

        elif mem_instr == self.MEM_Z_Q:
            q_val = self.Q.get()
            if q_val & 0x20:
                q_val -= 0x40
            base_address = self.getZ() + q_val


        # Apply Pre-decrement BEFORE accessing memory if mode requires it
        mode = self.IncDec.get()
        if pointer_name in ("X", "Y", "Z", "SP") and mode == self.INC_PRE_DEC:
            base_address -= 1


        return base_address & 0xFFFF, pointer_name

    # ==========================================================
    # Address update logic
    # ==========================================================

    def updatePointer(self, ptr_name):
        if ptr_name is None or ptr_name == "ROM":
            return

        mode = self.IncDec.get()
        if mode == self.INC_NONE:
            return

        if ptr_name == "X":
            val = self.getX()
            self.setX(val - 1 if mode == self.INC_PRE_DEC else val + 1)
        elif ptr_name == "Y":
            val = self.getY()
            self.setY(val - 1 if mode == self.INC_PRE_DEC else val + 1)
        elif ptr_name == "Z":
            val = self.getZ()
            self.setZ(val - 1 if mode == self.INC_PRE_DEC else val + 1)
        elif ptr_name == "SP":
            val = self.getSP()
            self.setSP(val - 1 if mode == self.INC_PRE_DEC else val + 1)


    # ==========================================================
    # Data source selection
    # ==========================================================

    def selectWriteData(self):
        sel = self.InputSelect.get()

        if sel == self.INPUT_DATABUS:

            return self.mem.read_data.get() 
        elif sel == self.INPUT_RESL:
            return self.ResL.get()
        elif sel == self.INPUT_RESH:
            return self.ResH.get()
        elif sel == self.INPUT_GENERAL:
            return self.GeneralInput.get()
        return 0

    # ==========================================================
    # Main clocked behavior
    # ==========================================================

    def clock(self):
        # ----------------------------------------------
        # 0. Reset
        # ----------------------------------------------
        if self.reset.get():
            self.XregL = 0
            self.XregH = 0
            self.YregL = 0
            self.YregH = 0
            self.ZregL = 0
            self.ZregH = 0
            self.SPL = self.SPH = 0
            self.BusData = 0
            
            self.RegisterOut.prepare(0)
            self.mem.address.prepare(0)
            self.mem.write_data.prepare(0)
            return

        # ----------------------------------------------
        # 1. Address generation
        # ----------------------------------------------
        # Address must be asserted to the bus first so the memory can react
        address, pointer_name = self.selectAddress()
        self.mem.address.prepare(address)

        # ----------------------------------------------
        # 2. Memory operation & BusData latching
        # ----------------------------------------------
        rw = self.ReadWrite.get()

        if rw:
            # WRITE: Latch data from MUX and send to memory
            self.BusData = self.selectWriteData()
            self.mem.write_data.prepare(self.BusData)
            self.mem.read.prepare(0)
            self.mem.write.prepare(1)
        else:
            # READ: Latch data returned by the memory model (not the address bus)
            self.BusData = self.mem.read_data.get()
            self.mem.read.prepare(1)
            self.mem.write.prepare(0)

        # Forward the memory handshake signal to the ControlBox
        self.Resp.prepare(self.mem.resp.get())

        # The schematic shows BusData routing directly to RegisterOut
        self.RegisterOut.prepare(self.BusData)

        # ----------------------------------------------
        # 3. Register loading
        # ----------------------------------------------
        if self.WE.get():
            load_sel = self.LoadingMux.get()
            data = self.BusData & 0xFF

            if load_sel == self.LOAD_XL: self.XregL = data
            elif load_sel == self.LOAD_XH: self.XregH = data
            elif load_sel == self.LOAD_YL: self.YregL = data
            elif load_sel == self.LOAD_YH: self.YregH = data
            elif load_sel == self.LOAD_ZL: self.ZregL = data
            elif load_sel == self.LOAD_ZH: self.ZregH = data
            elif load_sel == self.LOAD_SPL: self.SPL = data
            elif load_sel == self.LOAD_SPH: self.SPH = data

        # ----------------------------------------------
        # 4. Pointer update
        # ----------------------------------------------
        self.updatePointer(pointer_name)